# Generated by Django 4.2.4 on 2023-08-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_administrado',
            new_name='usuario_administrador',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(upload_to='perfil', verbose_name='Imagen de perfil'),
        ),
    ]
