# Generated by Django 4.2.4 on 2023-08-18 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_Categoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de categoria')),
                ('nombre_Categoria', models.CharField(max_length=20, verbose_name='ID del producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_Producto', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID del producto')),
                ('nombre_P', models.CharField(max_length=20, verbose_name='ID del producto')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('imagen', models.ImageField(upload_to='...\\static\\img\\Productos', verbose_name='foto de la carta')),
                ('precio', models.IntegerField(verbose_name='Precio del Producto')),
                ('id_Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
