# Generated by Django 4.2.5 on 2023-10-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_Producto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos/', verbose_name='Foto de la carta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_P',
            field=models.CharField(max_length=20, verbose_name='Nombre del producto'),
        ),
    ]
