# Generated by Django 4.2.7 on 2023-11-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_Venta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del producto')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre DEl comprador')),
                ('fecha', models.CharField(max_length=50, verbose_name='fecha ')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
            ],
        ),
    ]
