# Generated by Django 4.2.7 on 2023-11-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='productos',
            field=models.TextField(default='', verbose_name='Productos Seleccionados'),
        ),
    ]
