# Generated by Django 4.2.7 on 2023-11-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_venta_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(default='en tienda', max_length=20, verbose_name='Estado del producto '),
        ),
        migrations.AddField(
            model_name='venta',
            name='nombre_usuario',
            field=models.CharField(default='', max_length=20, verbose_name='Nombre DEl comprador'),
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.IntegerField(default=0, verbose_name='total del producto'),
        ),
    ]
