# Generated by Django 4.2.7 on 2023-11-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_venta_estado_venta_nombre_usuario_venta_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='direccion',
            field=models.CharField(default='', max_length=50, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='venta',
            name='region',
            field=models.CharField(default='', max_length=50, verbose_name='Email'),
        ),
    ]
