# Generated by Django 4.2.7 on 2023-11-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_venta_direccion_venta_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[(1, 'En tienda'), (2, 'Enviado'), (3, 'Entregado')], default=1, max_length=20),
        ),
    ]
