# Generated by Django 4.2.7 on 2023-11-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_venta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(default='En tienda', max_length=20),
        ),
    ]
