# Generated by Django 4.2.7 on 2023-11-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_venta_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del producto')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del evento')),
                ('fecha', models.CharField(max_length=20, verbose_name='Fecha evento')),
                ('precio', models.IntegerField(verbose_name='Precio del evento')),
                ('foto', models.ImageField(upload_to='productos/', verbose_name='Foto de la carta')),
            ],
        ),
    ]
