# Generated by Django 4.2.7 on 2023-11-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(default='sin Descripcion', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.ImageField(blank=True, upload_to='productos/', verbose_name='Foto de la carta'),
        ),
    ]
