# Generated by Django 4.2.7 on 2023-11-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_evento_descripcion_alter_evento_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hora',
            field=models.CharField(default='00:00', max_length=20, verbose_name='Hora'),
        ),
    ]
